from poke_env.battle.pokemon_type import PokemonType
from poke_env.battle.weather import Weather
from poke_env.battle.side_condition import SideCondition
from poke_env.battle.status import Status
from poke_env.battle.move_category import MoveCategory

POKEMON_TYPE = {
    PokemonType.BUG: 0,
    PokemonType.DARK: 1,
    PokemonType.DRAGON: 2,
    PokemonType.ELECTRIC: 3,
    PokemonType.FAIRY: 4,
    PokemonType.FIGHTING: 5,
    PokemonType.FIRE: 6,
    PokemonType.FLYING: 7,
    PokemonType.GHOST: 8,
    PokemonType.GRASS: 9,
    PokemonType.GROUND: 10,
    PokemonType.ICE: 11,
    PokemonType.NORMAL: 12,
    PokemonType.POISON: 13,
    PokemonType.PSYCHIC: 14,
    PokemonType.ROCK: 15,
    PokemonType.STEEL: 16,
    PokemonType.WATER: 17,
    PokemonType.THREE_QUESTION_MARKS: 12,
    PokemonType.STELLAR: 12,
}

WEATHER = {
    Weather.DESOLATELAND : 0,
    Weather.DELTASTREAM : 1,
    Weather.HAIL : 2,
    Weather.PRIMORDIALSEA : 3,
    Weather.RAINDANCE : 4,
    Weather.SANDSTORM : 5,
    Weather.SNOWSCAPE : 6,
    Weather.SUNNYDAY : 7,
}

STACK_HAZARD ={
    SideCondition.SPIKES:0,
    SideCondition.TOXIC_SPIKES:1,
}

NOT_STACK_HAZARD ={
    SideCondition.STEALTH_ROCK:2,
    SideCondition.STICKY_WEB:3
}

EXPIRE_CONDITION = {
    SideCondition.AURORA_VEIL:4,
    SideCondition.LIGHT_SCREEN:5,
    SideCondition.LUCKY_CHANT:6,
    SideCondition.MIST:7,
    SideCondition.REFLECT:8,
    SideCondition.SAFEGUARD:9,
    SideCondition.TAILWIND:10,
}

STATUS = {
    Status.BRN :0,
    Status.FRZ :1,
    Status.PAR :2,
    Status.PSN :3,
    Status.SLP :4,
    Status.TOX :5,
}

BASE_STAT = {
    "atk":0,
    "def":1,
    "spa":2,
    "spd":3,
    "spe":4,
    "hp": 5,
}

BOOST = {
    "atk":0,
    "def":1,
    "spa":2,
    "spd":3,
    "spe":4,
    "accuracy": 5,
    "evasion":6,
}

MOVE_CATEGORY = {
    MoveCategory.PHYSICAL: 0,
    MoveCategory.SPECIAL: 1,
    MoveCategory.STATUS: 2,
}

ITEM = {
    "black belt": 0,
    "fist plate": 0,
    "black glasses": 1,
    "dread plate": 1,
    "charcoal": 2,
    "flame plate": 2,
    "dragon fang": 3,
    "draco plate": 3,
    "fairy feather": 4,
    "pixie plate": 4,
    "hard stone": 5, 
    "stone plate": 5,
    "magnet": 6,
    "zap plate" : 6,
    "metal coat": 7,
    "iron plate": 7,
    "miracle seed": 8,
    "meadow plate": 8,
    "mystic water": 9,
    "splash plate": 9,
    "never-melt-ice": 10,
    "icicle plate": 10,
    "poison barb": 11,
    "toxic plate": 11,
    "sharp beak": 12,
    "sky plate": 12,
    "silk scarf": 13,
    "blank plate": 13,
    "silver powder": 14,
    "insect plate": 14,
    "soft sand": 15,
    "earth plate": 15,
    "spell tag": 16,
    "spooky plate": 16,
    "twisted spoon": 17,
    "mind plate": 17,
    "occa berry": 18,
    "passho berry": 19,
    "wacan berry": 20,
    "rindo berry": 21,
    "yache berry": 22,
    "chople berry": 23,
    "kebia berry": 24,
    "shuca berry": 25,
    "coba berry": 26,
    "payapa berry": 27,
    "tanga berry": 28,
    "charti berry": 29,
    "kasib berry": 30,
    "haban berry": 31,
    "colbur berry": 32,
    "babiri berry": 33,
    "chilan berry": 34,
    "roseli berry": 35,
    "cheri berry": 36,
    "chesto berry": 37,
    "pecha berry": 38,
    "rawst berry": 39,
    "aspear berry": 40,
    "persium berry": 41,
    "lum berry": 42,
    "sitrus berry": 43,
    "ability shield": 44,
    "air balloon": 45,
    "assault vest": 46,
    "choice band": 47,
    "choice scarf": 48,
    "choice specs": 49,
    "clear amulet": 50,
    "covert cloak": 51,
    "damp rock": 52,
    "destiny knot": 53,
    "eject button": 54,
    "eject pack": 55,
    "expert belt": 56,
    "flame orb": 57,
    "focus sash": 58,
    "heat rock": 59,
    "heavy-duty boots": 60,
    "icy rock": 61,
    "iron ball": 62,
    "kings rock": 63,
    "lagging tail": 64,
    "life orb": 65,
    "loaded dice": 66,
    "mental herb": 67,
    "muscle band": 68,
    "power herb": 69,
    "protective pads": 70,
    "punching glove": 71,
    "quick claw": 72,
    "razor claw": 73,
    "razor fang": 74,
    "red card": 75,
    "rocky helmet": 76,
    "safety goggles": 77,
    "scope lens": 78,
    "shed shell": 79,
    "smoke ball": 80,
    "smooth rock": 81,
    "sticky barb": 82,
    "toxic orb": 83,
    "white herb": 84,
    "wide lens": 85,
    "wise glasses": 86,
    "zoom lens": 87
}

ABILITY ={
    "stench": 0,
    "drizzle": 1,
    "speed boost": 2,
    "battle armor": 3,
    "sturdy": 4,
    "damp": 5,
    "limber": 6,
    "sand veil": 7,
    "static": 8,
    "volt absorb": 9,
    "water absorb": 10,
    "oblivious": 11,
    "cloud nine": 12,
    "compound eyes": 13,
    "insomnia": 14,
    "color change": 15,
    "immunity": 16,
    "flash fire": 17,
    "shield dust": 18,
    "own tempo": 19,
    "suction cups": 20,
    "intimidate": 21,
    "shadow tag": 22,
    "rough skin": 23,
    "wonder guard": 24,
    "levitate": 25,
    "effect spore": 26,
    "synchronize": 27,
    "clear body": 28,
    "natural cure": 29,
    "lightning rod": 30,
    "serene grace": 31,
    "swift swim": 32,
    "chlorophyll": 33,
    "illuminate": 34,
    "trace": 35,
    "huge power": 36,
    "poison point": 37,
    "inner focus": 38,
    "magma armor": 39,
    "water veil": 40,
    "magnet pull": 41,
    "soundproof": 42,
    "rain dish": 43,
    "sand stream": 44,
    "pressure": 45,
    "thick fat": 46,
    "early bird": 47,
    "flame body": 48,
    "run away": 49,
    "keen eye": 50,
    "hyper cutter": 51,
    "pickup": 52,
    "truant": 53,
    "hustle": 54,
    "cute charm": 55,
    "plus": 56,
    "minus": 57,
    "forecast": 58,
    "sticky hold": 59,
    "shed skin": 60,
    "guts": 61,
    "marvel scale": 62,
    "liquid ooze": 63,
    "overgrow": 64,
    "blaze": 65,
    "torrent": 66,
    "swarm": 67,
    "rock head": 68,
    "drought": 69,
    "arena trap": 70,
    "vital spirit": 71,
    "white smoke": 72,
    "pure power": 73,
    "shell armor": 74,
    "air lock": 75,
    "tangled feet": 76,
    "motor drive": 77,
    "rivalry": 78,
    "steadfast": 79,
    "snow cloak": 80,
    "gluttony": 81,
    "anger point": 82,
    "unburden": 83,
    "heatproof": 84,
    "simple": 85,
    "dry skin": 86,
    "download": 87,
    "iron fist": 88,
    "poison heal": 89,
    "adaptability": 90,
    "skill link": 91,
    "hydration": 92,
    "solar power": 93,
    "quick feet": 94,
    "normalize": 95,
    "sniper": 96,
    "magic guard": 97,
    "no guard": 98,
    "stall": 99,
    "technician": 100,
    "leaf guard": 101,
    "klutz": 102,
    "mold breaker": 103,
    "super luck": 104,
    "aftermath": 105,
    "anticipation": 106,
    "forewarn": 107,
    "unaware": 108,
    "tinted lens": 109,
    "filter": 110,
    "slow start": 111,
    "scrappy": 112,
    "storm drain": 113,
    "ice body": 114,
    "solid rock": 115,
    "snow warning": 116,
    "honey gather": 117,
    "frisk": 118,
    "reckless": 119,
    "multitype": 120,
    "flower gift": 121,
    "bad dreams": 122,
    "pickpocket": 123,
    "sheer force": 124,
    "contrary": 125,
    "unnerve": 126,
    "defiant": 127,
    "defeatist": 128,
    "cursed body": 129,
    "healer": 130,
    "friend guard": 131,
    "weak armor": 132,
    "heavy metal": 133,
    "light metal": 134,
    "multiscale": 135,
    "toxic boost": 136,
    "flare boost": 137,
    "harvest": 138,
    "telepathy": 139,
    "moody": 140,
    "overcoat": 141,
    "poison touch": 142,
    "regenerator": 143,
    "big pecks": 144,
    "sand rush": 145,
    "wonder skin": 146,
    "analytic": 147,
    "illusion": 148,
    "imposter": 149,
    "infiltrator": 150,
    "mummy": 151,
    "moxie": 152,
    "justified": 153,
    "rattled": 154,
    "magic bounce": 155,
    "sap sipper": 156,
    "prankster": 157,
    "sand force": 158,
    "iron barbs": 159,
    "zen mode": 160,
    "victory star": 161,
    "turboblaze": 162,
    "teravolt": 163,
    "aroma veil": 164,
    "flower veil": 165,
    "cheek pouch": 166,
    "protean": 167,
    "fur coat": 168,
    "magician": 169,
    "bulletproof": 170,
    "competitive": 171,
    "strong jaw": 172,
    "refrigerate": 173,
    "sweet veil": 174,
    "stance change": 175,
    "gale wings": 176,
    "mega launcher": 177,
    "grass pelt": 178,
    "symbiosis": 179,
    "tough claws": 180,
    "pixilate": 181,
    "gooey": 182,
    "aerilate": 183,
    "parental bond": 184,
    "dark aura": 185,
    "fairy aura": 186,
    "aura break": 187,
    "primordial sea": 188,
    "desolate land": 189,
    "delta stream": 190,
    "stamina": 191,
    "wimp out": 192,
    "emergency exit": 193,
    "water compaction": 194,
    "merciless": 195,
    "shields down": 196,
    "stakeout": 197,
    "water bubble": 198,
    "steelworker": 199,
    "berserk": 200,
    "slush rush": 201,
    "long reach": 202,
    "liquid voice": 203,
    "triage": 204,
    "galvanize": 205,
    "surge surfer": 206,
    "schooling": 207,
    "disguise": 208,
    "battle bond": 209,
    "power construct": 210,
    "corrosion": 211,
    "comatose": 212,
    "queenly majesty": 213,
    "innards out": 214,
    "dancer": 215,
    "battery": 216,
    "fluffy": 217,
    "dazzling": 218,
    "soul-heart": 219,
    "tangling hair": 220,
    "receiver": 221,
    "power of alchemy": 222,
    "beast boost": 223,
    "rks system": 224,
    "electric surge": 225,
    "psychic surge": 226,
    "misty surge": 227,
    "grassy surge": 228,
    "full metal body": 229,
    "shadow shield": 230,
    "prism armor": 231,
    "neuroforce": 232,
    "intrepid sword": 233,
    "dauntless shield": 234,
    "libero": 235,
    "ball fetch": 236,
    "cotton down": 237,
    "propeller tail": 238,
    "mirror armor": 239,
    "gulp missile": 240,
    "stalwart": 241,
    "steam engine": 242,
    "punk rock": 243,
    "sand spit": 244,
    "ice scales": 245,
    "ripen": 246,
    "ice face": 247,
    "power spot": 248,
    "mimicry": 249,
    "screen cleaner": 250,
    "steely spirit": 251,
    "perish body": 252,
    "wandering spirit": 253,
    "gorilla tactics": 254,
    "neutralizing gas": 255,
    "pastel veil": 256,
    "hunger switch": 257,
    "quick draw": 258,
    "unseen fist": 259,
    "curious medicine": 260,
    "transistor": 261,
    "dragons maw": 262,
    "chilling neigh": 263,
    "grim neigh": 264,
    "as one": 266,
    "lingering aroma": 267,
    "seed sower": 268,
    "thermal exchange": 269,
    "anger shell": 270,
    "purifying salt": 271,
    "well-baked body": 272,
    "wind rider": 273,
    "guard dog": 274,
    "rocky payload": 275,
    "wind power": 276,
    "zero to hero": 277,
    "commander": 278,
    "electromorphosis": 279,
    "protosynthesis": 280,
    "quark drive": 281,
    "good as gold": 282,
    "vessel of ruin": 283,
    "sword of ruin": 284,
    "tablets of ruin": 285,
    "beads of ruin": 286,
    "orichalcum pulse": 287,
    "hadron engine": 288,
    "opportunist": 289,
    "cud chew": 290,
    "sharpness": 291,
    "supreme overlord": 292,
    "costar": 293,
    "toxic debris": 294,
    "armor tail": 295,
    "earth eater": 296,
    "mycelium might": 297,
    "hospitality": 298,
    "minds eye": 299,
    "embody aspect": 303,
    "toxic chain": 304,
    "supersweet syrup": 305,
    "tera shift": 306,
    "tera shell": 307,
    "teraform zero": 308,
    "poison puppeteer": 309
}
